README.md

#what
DB設計を記載
#why
- items
ユーザが出品および購入できるもの
- users
出品者および購入者の情報
- buys
どのユーザが購入したかを記録するテーブル
- images
itemがもつイメージ画像を格納するテーブル
- categorys
itemsが所属するcategoryのテーブル
- profiles
usersは個人情報であるが、profileは公開しても良いuser情報とする

[WIP]add database design

---

app/views/items/new.html.haml

Change items new   images path

---

app/views/items/new.html.haml

add asset_path

---

app/views/items/new.html.haml

ロゴが表示されない問題、解決中
今度はファイル名に拡張子を追加してデプロイ実験

change file name

---

README.md

DB設計を記載
ユーザが出品および購入できるもの
出品者および購入者の情報
どのユーザが購入したかを記録するテーブル
itemがもつイメージ画像を格納するテーブル
itemsが所属するcategoryのテーブル
usersは個人情報であるが、profileは公開しても良いuser情報とする
Reverts moripp/freemarket_sample_59b#10

Revert "[WIP]add database design"

---

README.md

スプリトレビューにていただいた指摘を反映させました。
また、記入漏れなどの確認も再度確認しました。
- image_id削除
- belongs_to :buy → has_one :buyに修正
- belongs_to :category追記
- belongs_to :profile→has_one :profileに修正
- belongs_to :credit_card→has_one :credit_cardに修正
- has_many :buys追加
- item_idカラム追加
- テーブル追加
- image_id削除
　→imagesテーブルの方でitem_idと紐づくため、このテーブルにはimage_idが不要のため
- belongs_to :buy → has_one :buyに修正
　→１つの情報を持つ場合は「belongs_to」ではなく「has_one」が適切なため
- belongs_to :category追記
　→記述漏れ
- belongs_to :profile→has_one :profileに修正
　→１つの情報を持つ場合は「belongs_to」ではなく「has_one」が適切なため
- belongs_to :credit_card→has_one :credit_cardに修正
　→１つの情報を持つ場合は「belongs_to」ではなく「has_one」が適切なため
- has_many :buys追加
　→記述漏れ
- item_idカラム追加
　→itemsではなく、imagesで紐づけることが適切のため追加。itemsからはimage_idを削除した。
- テーブル追加
　→記述漏れ

[WIP]edit DB design

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/items/_create.scss
app/controllers/items_controller.rb
app/views/items/create.html.haml

- 出品完了画面の追加
- 出品が正常に完了すると完了画面に遷移させる
- 出品が正常に終了したことがユーザーに伝わりやすいようにする

Add html   exihibit done page

---

app/controllers/items_controller.rb
app/models/image.rb
app/models/item.rb

- 出品時の入力項目にバリデーションをかける
- itemテーブル
- name: 40文字以下、空は通さない
- description: 1000文字以下、空は通さない
- price: 整数、300以上、9,999,999以下、空は通さない
- imageテーブル
- image: 空は通さない
- バリデーションで弾かれた場合は入力フォームに戻り、必要な項目のみ修正させる
- データベースに不適切なデータを入れさせない
- バリデーションに弾かれて入力フォームに戻ると、画像のアップロードボタンが消えてしまう
- 画像アップロードボタンはこの後見た目も修正予定なのでその時に問題を解決させる

Exhibit function  add validation

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/credit_cards/new.scss
app/controllers/credit_cards_controller.rb
app/views/credit_cards/new.html.haml
config/routes.rb
db/schema.rb

・クレジットカード未登録者がクレジットカード情報を登録する時の画面のマークアップ
・マイページ＞支払い方法
・ユーザーがメルカリで商品を購入するのに必要な機能だから。
左側の空白部分は他のメンバー待ちです。

Credit cards new action markup

---

app/assets/stylesheets/items/_show.scss
app/controllers/items_controller.rb
app/helpers/application_helper.rb
app/models/item.rb
app/models/user.rb
app/views/items/show.html.haml

- 商品詳細表示、サーバーサイド実装
- コントローラーでインスタンス定義
- hamlで必要な箇所、変数化
- リファクタイングの為helper追加
- 商品詳細ページに遷移した時にDBのデータが反映されるようにする為
##

[WIP] Item details function  server side

---

app/views/credit_cards/index.html.haml
app/views/credit_cards/index1.html.haml
app/views/credit_cards/new.html.haml
app/views/layouts/_header.html.haml
app/views/mypages/_left.html.haml
app/views/profiles/index.html.haml
app/views/profiles/new.html.haml

・プロフィール2ページに「左リスト」と「出品ボタン」の追加
・クレジットカード3ページに「左リスト」と「出品ボタン」の追加
・「左リスト」に適切なリンク先を設定
>・プロフィール2ページに「左リスト」と「出品ボタン」の追加
>・クレジットカード3ページに「左リスト」と「出品ボタン」の追加
>・「左リスト」に適切なリンク先を設定
→左リスト実装が完成されたため追加しました。

Add mypages left markup

---

app/controllers/home_controller.rb
app/views/home/_content_wrapper.html.haml
app/views/layouts/_item_list.html.haml

[what]出品された商品の一覧を表示する機能
[why]出品された商品の一覧を表示させる

[WIP]出品した商品一覧機能の実装

---

app/assets/stylesheets/logout/_logout.scss
app/views/logout/index.html.haml

- ログアウトページからログアウトできるように修正
- ログアウトページからログアウトできるように修正
>ログアウトページのマークアップが完了したため、ログアウトするためのメソッドを追加しました。
[![Screenshot from Gyazo](https://gyazo.com/c361aba34889eb2c9adb7c578e1bab4b/raw)](https://gyazo.com/c361aba34889eb2c9adb7c578e1bab4b)

[wip]Mypage logout btn

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/sitemap/_index.scss
app/controllers/sitemap_controller.rb
app/views/sitemap/index.html.haml
db/schema.rb

- デプロイ後のtable内の情報を見ることを容易にするためにサイトマップをアップデート
- デプロイ後のtable内の情報を見ることを容易にするためにサイトマップをアップデート
> 開発中に確認をスムーズにするため
※sitemapファイル全般は開発終了後に削除します。

[wip]Sitemap update

---

app/controllers/credit_cards_controller.rb
app/controllers/items_controller.rb
app/controllers/mypages_controller.rb

[what]  ・アイテム詳細画面をログインしなければみれなかった状態を、ログインしなくても見れるよう修正した　
　　　　・アイテム一覧ページにおいて、ログインしていなくても購入と出品ができてしまっていたのをログインしなければログイン画面に遷移するよう修正した
　　　　・マイページとクレジットカード画面も同様にログインしなくてもサイトマップから見れる状態になっていたので、ログイン画面に遷移させるよう訂正いたしました
https://gyazo.com/e3be52d0ef1b2e0cd8bd651729ef8279
https://gyazo.com/58c81f6595c4bd37f354c9b083ef282d

[商品一覧画面における条件分岐」

---

app/views/signup/_footer.html.haml
app/views/signup/_header.html.haml
db/schema.rb

[what] 画像が表示されていなかったsignupページのviewフアイルのヘッダーとフッターのコードにsvg'を追記しました。デプロイ完了したら表示されるようになったかを確認したいので教えてください！

[ログイン画面フッターとヘッダーの画像が表示されない]

---

app/controllers/profiles_controller.rb
app/views/profiles/new.html.haml

Reverts moripp/freemarket_sample_59b#66
間違えてマージしてしまったので、もう一度ブランチ作ります

Revert "本人情報登録ページのサーバー実装" 

---

app/controllers/myitems_controller.rb

- 編集機能に不十分な点があった
- 編集機能は、①不要な画像を削除、②その後update、の2工程でできている
- ①が終了した後、②でトラブルが起きた場合、②の変更が反映されずに①の画像消去だけ反映されてしまう
- 上記の問題を解決する為、トランザクション追加
- ①と②の両方成功した時のみ、変更が反映されるようにする
- 予期せぬバグの混入を防ぐため
動画は価格を77にすることで、updateの段階でエラーが起きるようにしている
そしてエラーが起きているので画像は消去されずに残っている
https://gyazo.com/19740790bd5d640ed24f0fdbc4a0bb15

商品編集機能にトランザクション定義

---

app/assets/stylesheets/home/_content_wrapper.scss
app/controllers/home_controller.rb
app/views/home/_content_wrapper.html.haml

ホーム画面での商品画像のページネーションを実装した
ホーム画面で商品画像を５個以上表示させる為

ホーム画面でのpaginationの実装

---

app/controllers/items_controller.rb
app/models/item.rb
app/views/items/show.html.haml

・出品中（for_sale）であれば購入ができる
・購入されたらアイテムは購入できなくする
・フリマなので一度購入されたら同じ商品を購入できないようにするため。
[![Screenshot from Gyazo](https://gyazo.com/0457a43664bd53e8e4ec316acdc6f350/raw)](https://gyazo.com/0457a43664bd53e8e4ec316acdc6f350)

購入された商品は購入できない。
